name: 'shanghai_transport'
version: '1.0.0'
config-version: 2

# Profile name (must match profiles.yml)
profile: 'shanghai_transport'

# Flags for Databricks compatibility
flags:
  use_materialization_v2: true
  use_managed_iceberg: true

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target paths
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Variables
vars:
  source_catalog: "workspace"
  source_schema: "public"

# Model configurations
models:
  shanghai_transport:
    # Staging models - tables in public schema with stg_ prefix
    staging:
      +materialized: table
      +schema: public
      +enabled: true
    
    # Dimension models - tables in public schema with dim_ prefix
    dimensions:
      +materialized: table
      +schema: public
      +enabled: true
    
    # Fact models - incremental tables in public schema with fact_ prefix
    facts:
      +materialized: table
      +schema: public
      +incremental_strategy: merge
      +enabled: true
    
    # Marts models - tables in public schema with mart_ prefix
    marts:
      +materialized: table
      +schema: public
      +enabled: true

# Seeds configuration
seeds:
  shanghai_transport:
    +schema: public
    +enabled: true

# Tests configuration
tests:
  shanghai_transport:
    +enabled: true

# Documentation
docs-paths: ["docs"]

